
package com.bdd.soap.stubs;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AddTwoNumbers", targetNamespace = "http://service.soap.bdd.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AddTwoNumbers {


    /**
     * 
     * @param num1
     * @param num2
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "addNumbersReturn", targetNamespace = "http://service.soap.bdd.com")
    @RequestWrapper(localName = "addNumbers", targetNamespace = "http://service.soap.bdd.com", className = "com.bdd.soap.service.AddNumbers")
    @ResponseWrapper(localName = "addNumbersResponse", targetNamespace = "http://service.soap.bdd.com", className = "com.bdd.soap.service.AddNumbersResponse")
    public int addNumbers(
        @WebParam(name = "num1", targetNamespace = "http://service.soap.bdd.com")
        int num1,
        @WebParam(name = "num2", targetNamespace = "http://service.soap.bdd.com")
        int num2);

}
